-- IN ORACLE-SQL, THE STRFTIME('%Y-%m-%d', X) WOULD BE WRITTEN AS TO_DATE(X) AND 
-- IT WOULD NOT BE NECESSARY TO EXPLICITLY TELL THIS IS A '2021-04-27' DATE

-- OBS: IT WOULD BE POSSIBLE TO DIVIDE AMOUNT BY FINAL_RATE, I CHOSE TO MAKE THE INVERSE RATE EXPLICIT 
-- IN A PERFORMANCE SITUATION, I WOULD HAVE THAT IMPLICIT AND REDUCE THE AMOUNT OF OPERATIONS
SELECT 
    STRFTIME('%Y-%m-%d', TRANSACTIONS.CREATED_AT) AS TRANSACTION_DATE,
    TRANSACTIONS.CCY,
    SUM(CASE WHEN TRANSACTIONS.AMOUNT < 0 THEN TRANSACTIONS.AMOUNT * (1 / RATES.FINAL_RATE) ELSE 0.0 END) AS DEBITS_GBP
FROM TRANSACTIONS  TRANSACTIONS
LEFT JOIN RATES RATES
    ON STRFTIME('%Y-%m-%d', TRANSACTIONS.CREATED_AT) = RATES.RATE_DATE
    AND TRANSACTIONS.CCY = RATES.INTO_CURRENCY_CODE
WHERE STRFTIME('%Y-%m-%d', TRANSACTIONS.CREATED_AT) = DATE('2021-04-27')
GROUP BY
    STRFTIME('%Y-%m-%d', TRANSACTIONS.CREATED_AT),
    TRANSACTIONS.CCY
